# Dockerfile à modifier pour ajouter des librairies et utilitaires nécessaires
# à la compilation de tous les codes
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libpth-dev
RUN apt-get install -y libpthread-stubs0-dev
RUN apt-get install -y strace
RUN apt-get install -y ltrace